Routing network request to specific network
Catfriend1/syncthing-android pull request #914
Opened 2022-09-28 07:36 UTC by xz-dev

I set wifi only, in the first few days, my home wifi dns broken when I don't know, but it connect.
So, syncthing is running and android system routing all the request to mobile data, and consumed my entire traffic allowance at one night.
The patch is for the situation.

2022-09-28 08:22 UTC, xz-dev commented
Need clear binding when stop synvthing

2022-09-28 08:42 UTC, Catfriend1 commented
Cool, thanks for working on it :-).

2022-09-28 10:43 UTC, xz-dev commented
> Need clear binding when stop syncthing

Done. but only working on SDK 23 and up

2022-09-28 20:11 UTC, Catfriend1 requested changes

2022-09-28 20:11 UTC, Catfriend1 commented on app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java
> +            clearBindNetwork();
Why is this required? I see below that you clearBindNetwork() in killSyncthing() .

2022-09-28 20:11 UTC, Catfriend1 commented on app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java
> -                PowerManager.PARTIAL_WAKE_LOCK,
Please remove this change. I'll do it in main.

2022-09-28 20:11 UTC, Catfriend1 commented on app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java
> +
Please do not reorder.

2022-09-28 20:11 UTC, Catfriend1 commented on app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java
> -import com.nutomic.syncthingandroid.service.Constants;
I'll do this in main, thanks.

2022-09-28 20:11 UTC, Catfriend1 commented
> > Need clear binding when stop syncthing
> 
> Done. but only working on SDK 23 and up

That's no problem.

2022-09-28 20:17 UTC, Catfriend1 commented on app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java
> +            clearBindNetwork();
Ah ok, it's in case the SyncthingNative exits by itself (due to error etc.)

2022-09-28 20:23 UTC, Catfriend1 commented on app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java
> +            if (!(mPreferences.getBoolean(Constants.PREF_RUN_ON_WIFI, true)
What about this? Can you please explain what the positive cases are and why another case (e.g. WiFi = on, mobile data = off) doesn't need the active network binding?

```
            if (!mPreferences.getBoolean(Constants.PREF_RUN_ON_WIFI, true) ||
                    mPreferences.getBoolean(Constants.PREF_RUN_ON_MOBILE_DATA, true))) {
```

2022-09-29 02:53 UTC, xz-dev commented on app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java
> +            if (!(mPreferences.getBoolean(Constants.PREF_RUN_ON_WIFI, true)
As [that](https://github.com/Catfriend1/syncthing-android/blob/02f542691c58668de895d06f6cb3178b1d21a30e/app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java#L132) say
1. set running in WiFi = on, mobile data = off -> only wifi
2. set running in WiFi = off, mobile data = on -> only mobile data

2022-09-29 02:55 UTC, xz-dev commented on app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java
> +            if (!(mPreferences.getBoolean(Constants.PREF_RUN_ON_WIFI, true)
No logical operators because it looks verbose.

2022-09-29 07:50 UTC, Catfriend1 commented on app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java
> +            if (!(mPreferences.getBoolean(Constants.PREF_RUN_ON_WIFI, true)
If ((wifi && !mobile) || (!wifi && mobile)) {
    bindNetwork()
}

Is this the same as what you intend? Can we please make it look like this? I feel uncomfortable reading a !(! && .) statement.

2022-09-29 07:53 UTC, Catfriend1 commented
I also think bindNetwork will not be executed if run conditions are changed by the user while Syncthing is running. But given that this is expected to rarely happen, mainly on initial setup, we can skip writing code for it now and if it really turns out important do it later.

2022-09-29 08:00 UTC, xz-dev commented
> I also think bindNetwork will not be executed if run conditions are changed by the user while Syncthing is running. But given that this is expected to rarely happen, mainly on initial setup, we can skip writing code for it now and if it really turns out important do it later. Plus, using mobile data is default off.

Yeah, I agree with you. Basically, I just do not want make my code as simple as possible.

2022-09-29 10:54 UTC, Catfriend1 commented
Perfect. Any more testing needed? Or should I merge this as is?

2022-09-29 17:55 UTC, Catfriend1 approved these changes

2022-09-29 17:56 UTC, merged

2022-09-29 17:56 UTC, Catfriend1 commented
Thanks for your contributen :-). 🚀

2025-03-13 21:59 UTC, LinuxOnTheDesktop commented
@xz-dev: please see [here](https://github.com/Catfriend1/syncthing-android/issues/1306). (You might get a notification from there and from here. If so, I apologise.)

2025-03-14 01:30 UTC, xz-dev commented
> @xz-dev: please see [here](https://github.com/Catfriend1/syncthing-android/issues/1306). (You might get a notification from there and from here. If so, I apologise.)

Yeah, I got notification. In GitHub, `at` is enough to notify someone.