Add Run Only On Vpn condition
Catfriend1/syncthing-android pull request #938
Opened 2022-11-16 21:43 UTC by androw

Implements #928

2022-11-16 21:53 UTC, Catfriend1 requested changes
Thanks for helping here.

Should this default to true? 
```mPreferences.getBoolean(Constants.PREF_RUN_ONLY_ON_VPN, true);```

2022-11-16 21:56 UTC, Catfriend1 reviewed
Thanks for helping here.

Should this default to true? 
```mPreferences.getBoolean(Constants.PREF_RUN_ONLY_ON_VPN, true);```

2022-11-16 21:56 UTC, Catfriend1 commented on app/src/main/java/com/nutomic/syncthingandroid/service/Constants.java
> +    public static String DYN_PREF_OBJECT_SYNC_ONLY_ON_WIFI(String objectPrefixAndId) {
ON_VPN?

2022-11-17 20:08 UTC, androw commented on app/src/main/java/com/nutomic/syncthingandroid/service/Constants.java
> +    public static String DYN_PREF_OBJECT_SYNC_ONLY_ON_WIFI(String objectPrefixAndId) {
Both fixed!

2022-11-17 21:55 UTC, androw commented
Did some testing on my side. We shouldn't merge this before moving to minSdkVersion 23.

2022-12-06 21:52 UTC, Zulgrib commented
How do you tell if it is a real vpn or a fake vpn to filter ads served by localhost? 

The WiFi ssid restriction is a good example of how I would expect things to work as a user, but I don't know if something similar is possible.

2022-12-06 22:35 UTC, androw commented
It's hard to cover every usecases. I have check rapidly and didn't find a way to check for the VPN name in a human interpretable form.
Let me know if you find something but I don't have a lot of time to work on this.

2022-12-07 09:01 UTC, Zulgrib commented
VPN apps are supposed to advertise a specific intent, I don't know if it can be used to find and list them and/or if it is possible to query if that specific vpn software is currently providing the tunnel interface.

2022-12-08 19:15 UTC, androw commented
Looks like we can now merge this

2022-12-08 19:37 UTC, Catfriend1 commented
How important is this? minSdkVersion 23
I remember we are on minSdk 21.

2022-12-08 19:51 UTC, androw commented
Ooops looks like I messed up between local and main branches. Sorry :/

2022-12-13 06:35 UTC, Catfriend1 commented
No problem

2022-12-15 22:19 UTC, androw commented
@kahhong you can find a debug build here: https://static.androw.eu/syncthing-debug.apk.zip
Feel free to test!

2022-12-15 23:28 UTC, Catfriend1 commented
I'm all ears for the result :)

2023-02-26 15:12 UTC, androw commented
Friendly bump!

2023-02-26 15:31 UTC, Catfriend1 commented
How is the community feedback on this?

2023-02-28 08:11 UTC, kahhong commented
Works like a charm (Syncthing 1.22.2-preview.1). 

Syncthing sleeps when VPN is disconnected.

Syncthing starts when VPN is connected.

2023-03-04 20:24 UTC, Catfriend1 commented
:-)

2023-03-05 03:19 UTC, kahhong commented
Works like a charm (Syncthing 1.22.2-preview.1). 

Syncthing sleeps when VPN is disconnected.

Syncthing starts when VPN is connected.

Edit: test

2023-03-05 06:27 UTC, androw commented
I've asked myself during implementation.
It's possible but it's one more option to add.
Maybe the better would be to rewrite the condition system to allow for cumulative or exclusive condition.

2023-03-05 11:43 UTC, Catfriend1 commented
@androw Yep, that is also on my mind. Many good wishes for the condition "system" are on the way looking at the issue tracker. Your solution is good and I'd like to make it available to users, but I'm pretty unsure about the easyness for new users to understand the "negated" condition.

2023-03-05 13:00 UTC, kahhong commented
I did a bit of brainstorming and would like to share my thoughts. I think it would be diminishing returns to implement a fully functional bitwise logic operations (AND/OR/XOR) as I don't see any more network-related conditions to add.

Before "Run on VPN" condition was added, the run conditions were sufficient on an allow/deny basis (checked/unchecked). As far as i can tell, there was no bitwise logic involved. However, "Run on VPN" condition added more complexity to the logic of conditions pertaining to the network-related conditions of the phone.

The reasonable permuatations of the 3 network-related conditions (VPN, Mobile Data and WiFi) are as follows:
[Reasonable Combinations]
- Wifi only
- Mobile Data only
- Wifi AND Mobile Data only
- VPN AND Wifi only
- VPN AND Mobile Data only
- VPN AND (Mobile Data OR Wifi)

Hence, I'd like to suggest we condense these conditions on the UI:
- Run only on VPN
- Run on Wi-Fi
- Run on mobile data

into a dropdown options mentioned in the list of Reasonable Combinations.

@Catfriend1 @androw do peer review my logic pls, thanks!

2023-03-05 16:31 UTC, androw commented
@Catfriend1 The "Run only on VPN" rule seems easy to understand.
@kahhong The 'I want to use VPN on mobile and I'm fine with VPN on my home wifi' rule seems an acceptable one and need a new condition "system". If I understand correctly, you're proposing to explicit the already existing possibilities?

2023-03-06 00:18 UTC, kahhong commented
@androw I also agree that the "Run only on VPN" option is easy to understand.


I'm not sure what you meant by "explicit the already existing possibilities." I'm thinking since VPN has added a layer of complexity therefore, exploring other possibilities to meet in the middle can help provide advanced functionalities and keep it easy for the users at the same time.

2023-06-11 11:38 UTC, Catfriend1 commented
> The reasonable permuatations of the 3 network-related conditions (VPN, Mobile Data and WiFi) are as follows: [Reasonable Combinations]
> 
> * Wifi only
> * Mobile Data only
> * Wifi AND Mobile Data only
> * VPN AND Wifi only
> * VPN AND Mobile Data only
> * VPN AND (Mobile Data OR Wifi)
> 
> Hence, I'd like to suggest we condense these conditions on the UI:
> 
> * Run only on VPN
> * Run on Wi-Fi
> * Run on mobile data

I think that would be the way to go here. The implementation is fine, but "run only" was the way we've worked a lot in the past to avoid it on the UI. Let's go "whitelist without blacklist" strategy.

2023-06-11 11:38 UTC, closed without merging

2023-06-11 11:38 UTC, Catfriend1 reviewed
See last comment